-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Categories
-- Defines broad groups like 'cafe', 'convenience', 'transport'
CREATE TABLE IF NOT EXISTS public.categories (
    id TEXT PRIMARY KEY, -- e.g. 'cafe'
    name TEXT NOT NULL
);

-- 2. Brands
-- Specific merchants where transactions happen
CREATE TABLE IF NOT EXISTS public.brands (
    id TEXT PRIMARY KEY, -- e.g. 'starbucks'
    name TEXT NOT NULL,
    category_id TEXT REFERENCES public.categories(id),
    icon_name TEXT -- 'Coffee', 'Bus', etc. for Lucide icons
);

-- 3. Cards
-- Credit/Debit card products
CREATE TABLE IF NOT EXISTS public.cards (
    id TEXT PRIMARY KEY, -- e.g. 'kb_nara'
    name TEXT NOT NULL,
    company TEXT NOT NULL,
    color TEXT, -- Tailwind class e.g. 'bg-yellow-500'
    -- limit_table: Logic for card-level monthly limits based on performance
    -- e.g. [{ "threshold": 300000, "limit": 20000 }, { "threshold": 500000, "limit": 30000 }]
    limit_table JSONB DEFAULT '[]'::jsonb
);

-- 4. Benefit Rules (The Core Engine)
-- Defines how and when a discount is applied
CREATE TABLE IF NOT EXISTS public.benefit_rules (
    id TEXT PRIMARY KEY, -- e.g. 'kb_star_20'
    card_id TEXT REFERENCES public.cards(id) ON DELETE CASCADE,
    
    -- Target Logic
    category TEXT REFERENCES public.categories(id), -- Fallback category if no brands specified
    included_brands TEXT[], -- Array of brand_ids, e.g. ['starbucks', 'twosome']
    excluded_brands TEXT DEFAULT NULL, -- Array of brand_ids to explicitly exclude
    
    -- Condition Logic
    platform_type TEXT DEFAULT 'ALL', -- 'ALL', 'ONLINE', 'OFFLINE', 'OFFICIAL_SITE'
    
    -- Grouping for Shared Limits (e.g. "Conv & Cafe share 5k limit")
    -- If multiple rules have the same shared_group_id, their usage is aggregated together.
    shared_group_id TEXT, 

    description TEXT, -- UI display e.g. "Starbucks 20%"
    detail TEXT, -- UI display e.g. "Min spend 10k, Max 4k"

    -- Complex Conditions
    -- min_spend: Minimum transaction amount
    -- min_performance: Specific performance requirement for this rule (overrides card default if needed)
    condition JSONB DEFAULT '{}'::jsonb, 

    -- Action Logic
    -- type: 'PERCENT', 'FLAT', 'FIXED_PRICE'
    -- value: 20 (%), 1000 (won), 6000 (won)
    -- max_discount: Cap per transaction
    action JSONB DEFAULT '{}'::jsonb,

    -- Frequency & Amount Limits
    -- daily_count, monthly_count, yearly_count
    -- monthly_amount: Max discount amount per month for this rule (or shared group)
    limit_config JSONB DEFAULT '{}'::jsonb
);

-- 5. User Card Performances
-- Tracks user's previous month spending per card to determine tier
CREATE TABLE IF NOT EXISTS public.user_card_performances (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    user_id UUID NOT NULL, -- References auth.users
    card_id TEXT REFERENCES public.cards(id) ON DELETE CASCADE,
    amount INTEGER DEFAULT 0, -- Previous month performance
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    UNIQUE(user_id, card_id)
);

-- 6. Transaction History
-- Logs payment records to calculate remaining limits
CREATE TABLE IF NOT EXISTS public.transaction_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL, -- References auth.users
    card_id TEXT REFERENCES public.cards(id),
    brand_id TEXT REFERENCES public.brands(id),
    rule_id TEXT REFERENCES public.benefit_rules(id), -- Null if no benefit applied
    
    amount INTEGER NOT NULL, -- Payment amount
    discount_amount INTEGER NOT NULL DEFAULT 0, -- Applied discount
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_history_user_date ON public.transaction_history(user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_history_rule ON public.transaction_history(rule_id);
