export const INITIAL_CATEGORIES = [
    { id: 'cafe', name: '카페/디저트' },
    { id: 'convenience', name: '편의점/마트' },
    { id: 'food', name: '외식/패스트푸드' },
    { id: 'delivery', name: '배달앱' },
    { id: 'life', name: '생활/잡화' },
    { id: 'shopping', name: '쇼핑/커머스' },
    { id: 'movie', name: '영화/엔터' },
    { id: 'subscription', name: '구독(OTT)' },
    { id: 'transport', name: '교통/통신' },
    { id: 'etc', name: '기타' },
];

export const INITIAL_BRANDS = [
    // Cafe
    { id: 'starbucks', name: '스타벅스', category_id: 'cafe', icon_name: 'Coffee' },
    { id: 'twosome', name: '투썸플레이스', category_id: 'cafe', icon_name: 'Coffee' },
    { id: 'mega', name: '메가MGC커피', category_id: 'cafe', icon_name: 'Coffee' },
    { id: 'compose', name: '컴포즈커피', category_id: 'cafe', icon_name: 'Coffee' },
    { id: 'paiks', name: '빽다방', category_id: 'cafe', icon_name: 'Coffee' },
    { id: 'ediya', name: '이디야', category_id: 'cafe', icon_name: 'Coffee' },
    { id: 'coffeebean', name: '커피빈', category_id: 'cafe', icon_name: 'Coffee' },
    { id: 'paulbassett', name: '폴바셋', category_id: 'cafe', icon_name: 'Coffee' },
    { id: 'angelinus', name: '엔제리너스', category_id: 'cafe', icon_name: 'Coffee' },
    { id: 'mammoth', name: '매머드커피', category_id: 'cafe', icon_name: 'Coffee' },
    { id: 'baskin_robbins', name: '배스킨라빈스', category_id: 'cafe', icon_name: 'IceCreamBowl' },
    { id: 'krispy_kreme', name: '크리스피크림', category_id: 'cafe', icon_name: 'Dessert' },
    { id: 'paris_baguette', name: '파리바게뜨', category_id: 'cafe', icon_name: 'Dessert' },
    { id: 'tous_les_jours', name: '뚜레쥬르', category_id: 'cafe', icon_name: 'Dessert' },
    { id: 'dunkin', name: '던킨', category_id: 'cafe', icon_name: 'Dessert' },
    { id: 'gongcha', name: '공차', category_id: 'cafe', icon_name: 'Coffee' },

    // Food
    { id: 'kfc', name: 'KFC', category_id: 'food', icon_name: 'Utensils' },
    { id: 'lotteria', name: '롯데리아', category_id: 'food', icon_name: 'Utensils' },
    { id: 'mcdonalds', name: '맥도날드', category_id: 'food', icon_name: 'Utensils' },
    { id: 'burgerking', name: '버거킹', category_id: 'food', icon_name: 'Utensils' },
    { id: 'momstouch', name: '맘스터치', category_id: 'food', icon_name: 'Utensils' },
    { id: 'subway', name: '써브웨이', category_id: 'food', icon_name: 'Utensils' },
    { id: 'outback', name: '아웃백', category_id: 'food', icon_name: 'Utensils' },
    { id: 'vips', name: 'VIPS', category_id: 'food', icon_name: 'Utensils' },
    { id: 'domino', name: '도미노피자', category_id: 'food', icon_name: 'Utensils' },
    { id: 'pizzahut', name: '피자헛', category_id: 'food', icon_name: 'Utensils' },
    { id: 'papa_johns', name: '파파존스피자', category_id: 'food', icon_name: 'Utensils' },

    // Delivery
    { id: 'baemin', name: '배달의민족', category_id: 'delivery', icon_name: 'ShoppingBag' },
    { id: 'yogiyo', name: '요기요', category_id: 'delivery', icon_name: 'ShoppingBag' },
    { id: 'ddaenggyo', name: '땡겨요', category_id: 'delivery', icon_name: 'ShoppingBag' },
    { id: 'coupangeats', name: '쿠팡이츠', category_id: 'delivery', icon_name: 'ShoppingBag' },

    // Convenience / mart
    { id: 'gs25', name: 'GS25', category_id: 'convenience', icon_name: 'Store' },
    { id: 'cu', name: 'CU', category_id: 'convenience', icon_name: 'Store' },
    { id: 'cu_event', name: 'CU 행사상품', category_id: 'convenience', icon_name: 'Store' },
    { id: 'emart24', name: '이마트24', category_id: 'convenience', icon_name: 'Store' },
    { id: 'seveneleven', name: '세븐일레븐', category_id: 'convenience', icon_name: 'Store' },
    { id: 'japan_convenience', name: '일본 3대 편의점', category_id: 'convenience', icon_name: 'Store' },
    { id: 'emart', name: '이마트', category_id: 'convenience', icon_name: 'ShoppingCart' },
    { id: 'homeplus', name: '홈플러스', category_id: 'convenience', icon_name: 'ShoppingCart' },
    { id: 'lotte_mart', name: '롯데마트', category_id: 'convenience', icon_name: 'ShoppingCart' },
    { id: 'vietnam_lottemart', name: '베트남 롯데마트', category_id: 'convenience', icon_name: 'ShoppingCart' },
    { id: 'hanaro_mart', name: '농협 하나로마트', category_id: 'convenience', icon_name: 'ShoppingCart' },
    { id: 'emart_traders', name: '이마트 트레이더스', category_id: 'convenience', icon_name: 'ShoppingCart' },
    { id: 'vic_market', name: '롯데 VIC마켓', category_id: 'convenience', icon_name: 'ShoppingCart' },

    // Life / shopping
    { id: 'oliveyoung', name: '올리브영', category_id: 'life', icon_name: 'Gift' },
    { id: 'daiso', name: '다이소', category_id: 'life', icon_name: 'Gift' },
    { id: 'beauty_hair', name: '미용실/뷰티업종', category_id: 'life', icon_name: 'Scissors' },
    { id: 'sports_leisure', name: '스포츠/레저업종', category_id: 'life', icon_name: 'Dumbbell' },
    { id: 'coupang', name: '쿠팡', category_id: 'shopping', icon_name: 'ShoppingBag' },
    { id: 'naver_plus_store', name: '네이버플러스 스토어', category_id: 'shopping', icon_name: 'ShoppingBag' },
    { id: 'musinsa', name: '무신사', category_id: 'shopping', icon_name: 'Shirt' },
    { id: 'zigzag', name: '지그재그', category_id: 'shopping', icon_name: 'Shirt' },
    { id: 'ably', name: '에이블리', category_id: 'shopping', icon_name: 'Shirt' },
    { id: 'kream', name: '크림(KREAM)', category_id: 'shopping', icon_name: 'Shirt' },
    { id: '29cm', name: '29CM', category_id: 'shopping', icon_name: 'Shirt' },
    { id: 'gmarket', name: 'G마켓', category_id: 'shopping', icon_name: 'ShoppingBag' },
    { id: 'auction', name: '옥션', category_id: 'shopping', icon_name: 'ShoppingBag' },
    { id: 'elevenst', name: '11번가', category_id: 'shopping', icon_name: 'ShoppingBag' },
    { id: 'gs_shop', name: 'GS SHOP', category_id: 'shopping', icon_name: 'ShoppingBag' },
    { id: 'cj_onstyle', name: 'CJ온스타일', category_id: 'shopping', icon_name: 'ShoppingBag' },
    { id: 'google_play', name: 'Google Play', category_id: 'shopping', icon_name: 'Gamepad2' },
    { id: 'app_store', name: 'App Store', category_id: 'shopping', icon_name: 'Smartphone' },
    { id: 'interpark_ticket', name: '인터파크 티켓', category_id: 'shopping', icon_name: 'Ticket' },

    // Book / exams
    { id: 'kyobo', name: '교보문고', category_id: 'shopping', icon_name: 'BookOpen' },
    { id: 'yes24', name: 'YES24', category_id: 'shopping', icon_name: 'BookOpen' },
    { id: 'aladin', name: '알라딘', category_id: 'shopping', icon_name: 'BookOpen' },
    { id: 'toeic', name: 'TOEIC', category_id: 'shopping', icon_name: 'GraduationCap' },
    { id: 'opic', name: 'OPIc', category_id: 'shopping', icon_name: 'GraduationCap' },
    { id: 'teps', name: 'TEPS', category_id: 'shopping', icon_name: 'GraduationCap' },
    { id: 'jpt', name: 'JPT', category_id: 'shopping', icon_name: 'GraduationCap' },
    { id: 'hsk', name: 'HSK', category_id: 'shopping', icon_name: 'GraduationCap' },

    // Transport / telecom / travel
    { id: 'transport_public', name: '버스/지하철', category_id: 'transport', icon_name: 'Bus' },
    { id: 'rail', name: '철도(KTX/SRT/ITX 등)', category_id: 'transport', icon_name: 'Train' },
    { id: 'intercity_bus', name: '고속/시외버스', category_id: 'transport', icon_name: 'BusFront' },
    { id: 'kakaot', name: '카카오T', category_id: 'transport', icon_name: 'CarTaxiFront' },
    { id: 'taxi', name: '택시', category_id: 'transport', icon_name: 'CarTaxiFront' },
    { id: 'gas_station', name: '주유소', category_id: 'transport', icon_name: 'Fuel' },
    { id: 'telecom', name: '통신요금', category_id: 'transport', icon_name: 'Smartphone' },
    { id: 'overseas_transport', name: '해외 대중교통', category_id: 'transport', icon_name: 'Plane' },
    { id: 'vietnam_grab', name: '베트남 Grab', category_id: 'transport', icon_name: 'CarTaxiFront' },

    // Movie / entertainment
    { id: 'cgv', name: 'CGV', category_id: 'movie', icon_name: 'Film' },
    { id: 'lotte_cinema', name: '롯데시네마', category_id: 'movie', icon_name: 'Film' },
    { id: 'lotte_world', name: '롯데월드', category_id: 'movie', icon_name: 'RollerCoaster' },
    { id: 'everland', name: '에버랜드', category_id: 'movie', icon_name: 'RollerCoaster' },
    { id: 'seoul_land', name: '서울랜드', category_id: 'movie', icon_name: 'RollerCoaster' },
    { id: 'caribbean', name: '캐리비안베이', category_id: 'movie', icon_name: 'Waves' },

    // Subscription
    { id: 'youtube', name: '유튜브/유튜브 프리미엄', category_id: 'subscription', icon_name: 'Tv' },
    { id: 'netflix', name: '넷플릭스', category_id: 'subscription', icon_name: 'Tv' },
    { id: 'tving', name: '티빙', category_id: 'subscription', icon_name: 'Tv' },
    { id: 'disney', name: '디즈니+', category_id: 'subscription', icon_name: 'Tv' },
    { id: 'naver_plus', name: '네이버플러스 멤버십', category_id: 'subscription', icon_name: 'Tv' },
    { id: 'coupang_wow', name: '쿠팡 와우 멤버십', category_id: 'subscription', icon_name: 'Tv' },
    { id: 'naver_webtoon', name: '네이버웹툰', category_id: 'subscription', icon_name: 'Tv' },

    // Military / overseas / etc
    { id: 'military_px', name: '군마트/PX', category_id: 'etc', icon_name: 'Shield' },
    { id: 'military_fitness', name: '군 체력단련장', category_id: 'etc', icon_name: 'Dumbbell' },
    { id: 'military_resort', name: '군 콘도/휴양시설', category_id: 'etc', icon_name: 'Hotel' },
    { id: 'airport_lounge', name: '공항 라운지', category_id: 'etc', icon_name: 'Plane' },
    { id: 'overseas_payment', name: '해외 가맹점', category_id: 'etc', icon_name: 'Globe2' },
    { id: 'overseas_atm', name: '해외 ATM', category_id: 'etc', icon_name: 'Landmark' },
    { id: 'master_travel_rewards', name: 'Mastercard Travel Rewards', category_id: 'etc', icon_name: 'Gift' },
    { id: 'usa_starbucks', name: '미국 스타벅스', category_id: 'cafe', icon_name: 'Coffee' },
    { id: 'etc_brand', name: '기타', category_id: 'etc', icon_name: 'MoreHorizontal' },
];

export const INITIAL_CARDS = [
    {
        id: 'shinhan_deep_dream',
        name: '신한 Deep Dream 체크카드',
        company: '신한카드',
        color: 'bg-sky-500',
        limit_table: [
            { threshold: 800000, limit: 30000 },
            { threshold: 400000, limit: 15000 },
            { threshold: 200000, limit: 5000 },
            { threshold: 0, limit: 0 },
        ],
    },
    {
        id: 'kb_nara',
        name: 'KB국민 나라사랑카드',
        company: 'KB국민카드',
        color: 'bg-yellow-500',
        limit_table: [
            { threshold: 1000000, limit: 50000 },
            { threshold: 500000, limit: 30000 },
            { threshold: 300000, limit: 20000 },
            { threshold: 200000, limit: 10000 },
            { threshold: 100000, limit: 5000 },
            { threshold: 0, limit: 0 },
        ],
    },
    {
        id: 'shinhan_heyoung',
        name: '신한 Hey Young 체크카드',
        company: '신한카드',
        color: 'bg-indigo-500',
        limit_table: [
            { threshold: 1000000, limit: 30000 },
            { threshold: 800000, limit: 20000 },
            { threshold: 500000, limit: 10000 },
            { threshold: 200000, limit: 5000 },
            { threshold: 0, limit: 0 },
        ],
    },
    {
        id: 'shinhan_sol',
        name: '신한 SOL트래블 체크카드',
        company: '신한카드',
        color: 'bg-blue-400',
        network: 'MASTERCARD',
        limit_table: [],
    },
    {
        id: 'shinhan_nara',
        name: '신한 나라사랑카드',
        company: '신한카드',
        color: 'bg-blue-600',
        limit_table: [
            { threshold: 1000000, limit: 50000 },
            { threshold: 700000, limit: 40000 },
            { threshold: 500000, limit: 30000 },
            { threshold: 200000, limit: 20000 },
            { threshold: 100000, limit: 5000 },
            { threshold: 0, limit: 0 },
        ],
    },
    {
        id: 'kb_nori2_student',
        name: 'KB국민 노리2 학생증체크카드',
        company: 'KB국민카드',
        color: 'bg-orange-500',
        limit_table: [
            { threshold: 800000, limit: 50000 },
            { threshold: 600000, limit: 40000 },
            { threshold: 400000, limit: 30000 },
            { threshold: 200000, limit: 20000 },
            { threshold: 0, limit: 0 },
        ],
    },
    {
        id: 'hana_nara',
        name: '하나 나라사랑카드',
        company: '하나카드',
        color: 'bg-emerald-500',
        limit_table: [
            { threshold: 1000000, limit: 50000 },
            { threshold: 500000, limit: 30000 },
            { threshold: 300000, limit: 20000 },
            { threshold: 200000, limit: 10000 },
            { threshold: 100000, limit: 5000 },
            { threshold: 0, limit: 0 },
        ],
    },
    {
        id: 'hana_travelog_student',
        name: '하나 트래블로그 학생증 체크카드',
        company: '하나카드',
        color: 'bg-teal-500',
        limit_table: [],
    },
];

export const INITIAL_RULES = [
    // 신한 Deep Dream 체크카드
    {
        id: 'dd_dream_mart',
        card_id: 'shinhan_deep_dream',
        category: 'convenience',
        included_brands: ['emart', 'homeplus', 'lotte_mart', 'hanaro_mart', 'emart_traders', 'vic_market'],
        description: 'DREAM 할인점 0.6% 적립',
        detail: '전월 20만원 이상, 월 통합 적립한도 적용. 온라인몰/SSM 제외',
        condition: { min_performance: 200000 },
        action: { type: 'PERCENT', value: 0.6 },
        limit_config: {},
    },
    {
        id: 'dd_dream_convenience_life',
        card_id: 'shinhan_deep_dream',
        category: 'convenience',
        included_brands: ['cu', 'gs25', 'seveneleven', 'oliveyoung', 'daiso'],
        description: 'DREAM 편의점·잡화 0.6% 적립',
        detail: '전월 20만원 이상, 월 통합 적립한도 적용. 최다 이용 DREAM 영역은 1.0%까지 가능',
        condition: { min_performance: 200000 },
        action: { type: 'PERCENT', value: 0.6 },
        limit_config: {},
    },
    {
        id: 'dd_dream_movie_cafe',
        card_id: 'shinhan_deep_dream',
        category: 'cafe',
        included_brands: [
            'starbucks',
            'twosome',
            'mega',
            'compose',
            'paiks',
            'ediya',
            'coffeebean',
            'paulbassett',
            'cgv',
            'lotte_cinema',
        ],
        description: 'DREAM 영화·커피 0.6% 적립',
        detail: '전월 20만원 이상, 월 통합 적립한도 적용. 커피 업종/CJ CGV/롯데시네마 대상',
        condition: { min_performance: 200000 },
        action: { type: 'PERCENT', value: 0.6 },
        limit_config: {},
    },
    {
        id: 'dd_dream_telecom',
        card_id: 'shinhan_deep_dream',
        category: 'transport',
        included_brands: ['telecom'],
        description: 'DREAM 이동통신 0.6% 적립',
        detail: '전월 20만원 이상, SKT/KT/LG U+ 이동통신 자동이체 대상',
        condition: { min_performance: 200000 },
        action: { type: 'PERCENT', value: 0.6 },
        limit_config: {},
    },
    {
        id: 'dd_dream_overseas',
        card_id: 'shinhan_deep_dream',
        category: 'etc',
        included_brands: ['overseas_payment'],
        description: 'DREAM 해외 0.6% 적립',
        detail: '전월 20만원 이상, 월 통합 적립한도 적용',
        condition: { min_performance: 200000 },
        action: { type: 'PERCENT', value: 0.6 },
        limit_config: {},
    },
    {
        id: 'dd_weekend_fuel',
        card_id: 'shinhan_deep_dream',
        category: 'transport',
        included_brands: ['gas_station'],
        description: '주말 주유 리터당 40원 적립',
        detail: '전월 20만원 이상, 월 주유금액 20만원까지. 주유량 정보가 필요해 자동 계산 제외',
        condition: { min_performance: 200000, manual_check_required: true, required_note: '리터당 적립이라 주유량 확인 필요' },
        action: { type: 'FLAT', value: 0 },
        limit_config: {},
        uses_card_limit: false,
    },
    {
        id: 'dd_taxi_day',
        card_id: 'shinhan_deep_dream',
        category: 'transport',
        included_brands: ['taxi'],
        description: '택시 1천원 할인',
        detail: '전월 20만원 이상, 매월 3·6·9일 제공. 날짜 조건이 있어 자동 계산 제외',
        condition: { min_performance: 200000, manual_check_required: true, required_note: '3·6·9일 택시 이용 조건 확인 필요' },
        action: { type: 'FLAT', value: 1000 },
        limit_config: {},
        uses_card_limit: false,
    },
    {
        id: 'dd_basic_all',
        card_id: 'shinhan_deep_dream',
        description: '국내외 전 가맹점 0.2% 적립',
        detail: '전월 실적/적립한도 없음. DREAM 영역 조건 미충족 시 기본 적립으로 적용',
        condition: {},
        action: { type: 'PERCENT', value: 0.2 },
        limit_config: {},
        uses_card_limit: false,
    },

    // KB국민 나라사랑카드 - 신규 발급 중단, 기존 보유자 사용 가능
    {
        id: 'kb_nara_px',
        card_id: 'kb_nara',
        category: 'etc',
        included_brands: ['military_px'],
        description: 'PX/군마트 5~20% 환급할인',
        detail: '전월 실적 없음, 월 최대 5만원. 금액/매장별 세부율은 별도 확인',
        condition: {},
        action: { type: 'PERCENT', value: 20, max_discount: 50000 },
        limit_config: { monthly_amount: 50000 },
        uses_card_limit: false,
    },
    {
        id: 'kb_nara_transport',
        card_id: 'kb_nara',
        category: 'transport',
        included_brands: ['transport_public'],
        description: '대중교통 20% 환급할인',
        detail: '버스/지하철 월 최대 1만원, 청년 서비스 통합한도 적용',
        condition: { min_performance: 100000 },
        action: { type: 'PERCENT', value: 20 },
        limit_config: { monthly_amount: 10000 },
    },
    {
        id: 'kb_nara_telecom',
        card_id: 'kb_nara',
        category: 'transport',
        included_brands: ['telecom'],
        description: '통신요금 2,500원 환급할인',
        detail: '자동납부 5만원 이상, 월 1회, 청년 서비스 통합한도 적용',
        condition: { min_spend: 50000, min_performance: 100000 },
        action: { type: 'FLAT', value: 2500 },
        limit_config: { monthly_count: 1, monthly_amount: 2500 },
    },
    {
        id: 'kb_nara_cgv',
        card_id: 'kb_nara',
        category: 'movie',
        included_brands: ['cgv'],
        description: 'CGV 35% 환급할인',
        detail: '1만원 이상, 건당 최대 7천원, 청년 서비스 통합한도 적용',
        condition: { min_spend: 10000, min_performance: 100000 },
        action: { type: 'PERCENT', value: 35, max_discount: 7000 },
        limit_config: {},
        platform_type: 'OFFICIAL_SITE',
    },
    {
        id: 'kb_nara_starbucks',
        card_id: 'kb_nara',
        category: 'cafe',
        included_brands: ['starbucks'],
        description: '스타벅스 20% 환급할인',
        detail: '1만원 이상, 건당 최대 4천원, 일부 매장 제외',
        condition: { min_spend: 10000, min_performance: 100000 },
        action: { type: 'PERCENT', value: 20, max_discount: 4000 },
        limit_config: {},
    },
    {
        id: 'kb_nara_book',
        card_id: 'kb_nara',
        category: 'shopping',
        included_brands: ['kyobo'],
        description: '교보문고 5% 환급할인',
        detail: '2만원 이상, 건당 최대 2,500원',
        condition: { min_spend: 20000, min_performance: 100000 },
        action: { type: 'PERCENT', value: 5, max_discount: 2500 },
        limit_config: {},
    },
    {
        id: 'kb_nara_food',
        card_id: 'kb_nara',
        category: 'food',
        included_brands: ['outback', 'vips'],
        description: '아웃백/VIPS 20% 환급할인',
        detail: '3만원 이상, 건당 최대 1만원',
        condition: { min_spend: 30000, min_performance: 100000 },
        action: { type: 'PERCENT', value: 20, max_discount: 10000 },
        limit_config: {},
    },
    {
        id: 'kb_nara_online_shopping',
        card_id: 'kb_nara',
        category: 'shopping',
        included_brands: ['gs_shop', 'cj_onstyle', 'gmarket', 'auction'],
        description: '홈쇼핑/온라인쇼핑 5% 환급할인',
        detail: '건당 최대 2,500원, 청년 서비스 통합한도 적용',
        condition: { min_performance: 100000 },
        action: { type: 'PERCENT', value: 5, max_discount: 2500 },
        limit_config: {},
        platform_type: 'ONLINE',
    },
    {
        id: 'kb_nara_language',
        card_id: 'kb_nara',
        category: 'shopping',
        included_brands: ['toeic', 'jpt'],
        description: '어학시험 2천원 환급할인',
        detail: '월 1회, 연 6회, 청년 서비스 통합한도 적용',
        condition: { min_performance: 100000 },
        action: { type: 'FLAT', value: 2000 },
        limit_config: { monthly_count: 1, yearly_count: 6, monthly_amount: 2000 },
    },
    {
        id: 'kb_nara_amusement',
        card_id: 'kb_nara',
        category: 'movie',
        included_brands: ['everland', 'lotte_world'],
        description: '놀이공원 50% 현장할인',
        detail: '3만원 이상 현장예매, 건당 최대 25,000원',
        condition: { min_spend: 30000, min_performance: 100000 },
        action: { type: 'PERCENT', value: 50, max_discount: 25000 },
        limit_config: {},
        platform_type: 'OFFLINE',
    },

    // 신한 Hey Young 체크카드
    {
        id: 'hy_transport',
        card_id: 'shinhan_heyoung',
        category: 'transport',
        included_brands: ['transport_public'],
        description: '대중교통 5% 캐시백',
        detail: '전월 20만원 이상, 월 최대 3천원. 티머니 충전 제외',
        condition: { min_performance: 200000 },
        action: { type: 'PERCENT', value: 5 },
        limit_config: { monthly_amount: 3000 },
    },
    {
        id: 'hy_telecom',
        card_id: 'shinhan_heyoung',
        category: 'transport',
        included_brands: ['telecom'],
        description: '통신요금 2천원 캐시백',
        detail: '전월 20만원 이상, 자동납부 5만원 이상, 월 1회',
        condition: { min_spend: 50000, min_performance: 200000 },
        action: { type: 'FLAT', value: 2000 },
        limit_config: { monthly_count: 1, monthly_amount: 2000 },
    },
    {
        id: 'hy_cgv',
        card_id: 'shinhan_heyoung',
        category: 'movie',
        included_brands: ['cgv'],
        description: 'CGV 5천원 캐시백',
        detail: '전월 20만원 이상, 2만원 이상 결제, 월 1회',
        condition: { min_spend: 20000, min_performance: 200000 },
        action: { type: 'FLAT', value: 5000 },
        limit_config: { monthly_count: 1, monthly_amount: 5000 },
    },
    {
        id: 'hy_conv',
        card_id: 'shinhan_heyoung',
        category: 'convenience',
        included_brands: ['gs25', 'cu', 'emart24'],
        description: '편의점 1천원 캐시백',
        detail: '전월 20만원 이상, 1만원 이상, 일 1회/월 5회',
        condition: { min_spend: 10000, min_performance: 200000 },
        action: { type: 'FLAT', value: 1000 },
        limit_config: { daily_count: 1, monthly_count: 5, monthly_amount: 5000 },
    },
    {
        id: 'hy_cafe',
        card_id: 'shinhan_heyoung',
        category: 'cafe',
        included_brands: ['starbucks', 'twosome', 'ediya', 'paulbassett', 'mega', 'paiks', 'coffeebean', 'angelinus'],
        description: '카페 1천원 캐시백',
        detail: '전월 20만원 이상, 1만원 이상, 일 1회/월 5회',
        condition: { min_spend: 10000, min_performance: 200000 },
        action: { type: 'FLAT', value: 1000 },
        limit_config: { daily_count: 1, monthly_count: 5, monthly_amount: 5000 },
    },
    {
        id: 'hy_food',
        card_id: 'shinhan_heyoung',
        category: 'food',
        included_brands: ['kfc', 'krispy_kreme', 'baskin_robbins'],
        description: '패스트푸드/디저트 1천원 캐시백',
        detail: '전월 20만원 이상, 1만원 이상, 일 1회/월 5회',
        condition: { min_spend: 10000, min_performance: 200000 },
        action: { type: 'FLAT', value: 1000 },
        limit_config: { daily_count: 1, monthly_count: 5, monthly_amount: 5000 },
    },
    {
        id: 'hy_delivery',
        card_id: 'shinhan_heyoung',
        category: 'delivery',
        included_brands: ['ddaenggyo'],
        description: '땡겨요 1천원 캐시백',
        detail: '전월 20만원 이상, 1만원 이상, 일 1회/월 5회',
        condition: { min_spend: 10000, min_performance: 200000 },
        action: { type: 'FLAT', value: 1000 },
        limit_config: { daily_count: 1, monthly_count: 5, monthly_amount: 5000 },
    },
    {
        id: 'hy_life',
        card_id: 'shinhan_heyoung',
        category: 'life',
        included_brands: ['oliveyoung', 'daiso'],
        description: '올리브영/다이소 1천원 캐시백',
        detail: '전월 20만원 이상, 1만원 이상, 일 1회/월 5회',
        condition: { min_spend: 10000, min_performance: 200000 },
        action: { type: 'FLAT', value: 1000 },
        limit_config: { daily_count: 1, monthly_count: 5, monthly_amount: 5000 },
    },
    {
        id: 'hy_subscription',
        card_id: 'shinhan_heyoung',
        category: 'subscription',
        included_brands: ['netflix', 'disney', 'tving'],
        description: 'OTT 1천원 캐시백',
        detail: '전월 20만원 이상, 1만원 이상 공식 정기결제, 일 1회/월 5회',
        condition: { min_spend: 10000, min_performance: 200000 },
        action: { type: 'FLAT', value: 1000 },
        limit_config: { daily_count: 1, monthly_count: 5, monthly_amount: 5000 },
        platform_type: 'OFFICIAL_SITE',
    },
    {
        id: 'hy_online_shopping',
        card_id: 'shinhan_heyoung',
        category: 'shopping',
        included_brands: ['coupang', 'coupangeats', 'musinsa', 'zigzag', 'ably', 'kream'],
        description: '온라인 쇼핑 1천원 캐시백',
        detail: '전월 20만원 이상, 2만원 이상, 일 1회/월 5회',
        condition: { min_spend: 20000, min_performance: 200000 },
        action: { type: 'FLAT', value: 1000 },
        limit_config: { daily_count: 1, monthly_count: 5, monthly_amount: 5000 },
        platform_type: 'ONLINE',
    },
    {
        id: 'hy_easy_pay',
        card_id: 'shinhan_heyoung',
        category: 'shopping',
        included_brands: [],
        description: '간편결제 1% 캐시백',
        detail: '전월 20만원 이상, 2만원 이상, 월 최대 5천원. 신한 SOL Pay/삼성페이/Hey Young Pay 결제 확인 필요',
        condition: { min_spend: 20000, min_performance: 200000, manual_check_required: true, required_note: '간편결제 수단 확인 필요' },
        action: { type: 'PERCENT', value: 1 },
        limit_config: { monthly_amount: 5000 },
    },

    // 신한 SOL트래블 체크카드
    {
        id: 'sol_overseas_fee',
        card_id: 'shinhan_sol',
        category: 'etc',
        included_brands: ['overseas_payment'],
        description: '해외 결제 수수료 면제',
        detail: '국제브랜드 1% + 해외서비스 0.2% 면제, 전월 실적 없음',
        condition: {},
        action: { type: 'PERCENT', value: 1.2 },
        limit_config: {},
        uses_card_limit: false,
    },
    {
        id: 'sol_overseas_transport',
        card_id: 'shinhan_sol',
        category: 'transport',
        included_brands: ['overseas_transport'],
        description: '해외 대중교통 1% 할인',
        detail: '컨택리스 해외 대중교통, 전월 실적 없음, 월 최대 3천원',
        condition: {},
        action: { type: 'PERCENT', value: 1 },
        limit_config: { monthly_amount: 3000 },
        uses_card_limit: false,
    },
    {
        id: 'sol_domestic_convenience',
        card_id: 'shinhan_sol',
        category: 'convenience',
        included_brands: ['cu', 'gs25', 'seveneleven', 'emart24'],
        description: '국내 편의점 5% 할인',
        detail: '전월 국내 30만원 이상, 오프라인 일 1회/월 3회, 월 최대 3천원',
        condition: { min_performance: 300000 },
        action: { type: 'PERCENT', value: 5 },
        limit_config: { daily_count: 1, monthly_count: 3, monthly_amount: 3000 },
        platform_type: 'OFFLINE',
    },
    {
        id: 'sol_domestic_transport',
        card_id: 'shinhan_sol',
        category: 'transport',
        included_brands: ['transport_public'],
        description: '국내 대중교통 1% 할인',
        detail: '전월 국내 30만원 이상, 월 최대 3천원',
        condition: { min_performance: 300000 },
        action: { type: 'PERCENT', value: 1 },
        limit_config: { monthly_amount: 3000 },
    },
    {
        id: 'sol_cu_event',
        card_id: 'shinhan_sol',
        category: 'convenience',
        included_brands: ['cu_event'],
        description: 'CU 행사상품 5% 즉시할인',
        detail: '전월 실적 없음, 건당 최대 2천원. 행사상품 전용',
        condition: {},
        action: { type: 'PERCENT', value: 5, max_discount: 2000 },
        limit_config: {},
        uses_card_limit: false,
        platform_type: 'OFFLINE',
    },
    {
        id: 'sol_lounge',
        card_id: 'shinhan_sol',
        category: 'etc',
        included_brands: ['airport_lounge'],
        description: '공항 라운지 무료',
        detail: '전월 국내 30만원 이상, 반기 1회/연 2회. 결제할인이 아니므로 자동 계산 제외',
        condition: { min_performance: 300000, manual_check_required: true, required_note: '라운지 이용권 혜택은 결제금액 계산 제외' },
        action: { type: 'FLAT', value: 0 },
        limit_config: { yearly_count: 2 },
        uses_card_limit: false,
    },

    // 신한 나라사랑카드
    {
        id: 'sh_nara_px',
        card_id: 'shinhan_nara',
        category: 'etc',
        included_brands: ['military_px'],
        description: 'PX/군마트 20% 할인',
        detail: '전월 실적 없음. 3만원 미만 결제는 일 1회/1천원 한도, 3만원 이상은 월 10만원 한도',
        condition: {},
        action: { type: 'PERCENT', value: 20, max_discount: 1000 },
        limit_config: { monthly_amount: 100000 },
        uses_card_limit: false,
    },
    {
        id: 'sh_nara_military_fitness',
        card_id: 'shinhan_nara',
        category: 'etc',
        included_brands: ['military_fitness', 'military_resort'],
        description: '군 체력단련장/휴양시설 20% 할인',
        detail: '전월 실적 없음, 월 최대 2만원',
        condition: {},
        action: { type: 'PERCENT', value: 20 },
        limit_config: { monthly_amount: 20000 },
        uses_card_limit: false,
    },
    {
        id: 'sh_nara_transport',
        card_id: 'shinhan_nara',
        category: 'transport',
        included_brands: ['transport_public'],
        description: '대중교통 20% 할인',
        detail: '전월 10만원 이상, 월 최대 5천원',
        condition: { min_performance: 100000 },
        action: { type: 'PERCENT', value: 20 },
        limit_config: { monthly_amount: 5000 },
    },
    {
        id: 'sh_nara_wide_transport',
        card_id: 'shinhan_nara',
        category: 'transport',
        included_brands: ['rail', 'intercity_bus'],
        description: '광역교통 10% 할인',
        detail: '전월 10만원 이상, KTX/ITX/새마을/무궁화·고속/시외버스, 월 최대 3천원',
        condition: { min_performance: 100000 },
        action: { type: 'PERCENT', value: 10 },
        limit_config: { monthly_amount: 3000 },
    },
    {
        id: 'sh_nara_kakaot',
        card_id: 'shinhan_nara',
        category: 'transport',
        included_brands: ['kakaot'],
        description: '카카오T 택시 10% 할인',
        detail: '전월 10만원 이상, 월 최대 2천원',
        condition: { min_performance: 100000 },
        action: { type: 'PERCENT', value: 10 },
        limit_config: { monthly_amount: 2000 },
    },
    {
        id: 'sh_nara_convenience',
        card_id: 'shinhan_nara',
        category: 'convenience',
        included_brands: ['gs25', 'cu'],
        description: '편의점 20% 할인',
        detail: '전월 10만원 이상, 오프라인 일 1회/월 5회, 건당 1천원·월 5천원 한도',
        condition: { min_performance: 100000 },
        action: { type: 'PERCENT', value: 20, max_discount: 1000 },
        limit_config: { daily_count: 1, monthly_count: 5, monthly_amount: 5000 },
        platform_type: 'OFFLINE',
    },
    {
        id: 'sh_nara_cafe',
        card_id: 'shinhan_nara',
        category: 'cafe',
        included_brands: ['starbucks', 'ediya', 'mega', 'paulbassett', 'compose', 'mammoth', 'paiks'],
        description: '카페 5% 할인',
        detail: '전월 10만원 이상, 일 1회/월 3회, 건당 2천원·월 6천원 한도',
        condition: { min_performance: 100000 },
        action: { type: 'PERCENT', value: 5, max_discount: 2000 },
        limit_config: { daily_count: 1, monthly_count: 3, monthly_amount: 6000 },
    },
    {
        id: 'sh_nara_book',
        card_id: 'shinhan_nara',
        category: 'shopping',
        included_brands: ['aladin', 'yes24'],
        description: '온라인 서점 5% 할인',
        detail: '전월 10만원 이상, 공식 홈페이지/앱, 월 최대 6천원',
        condition: { min_performance: 100000 },
        action: { type: 'PERCENT', value: 5 },
        limit_config: { monthly_amount: 6000 },
        platform_type: 'OFFICIAL_SITE',
    },
    {
        id: 'sh_nara_telecom',
        card_id: 'shinhan_nara',
        category: 'transport',
        included_brands: ['telecom'],
        description: '통신요금 5% 할인',
        detail: '전월 10만원 이상, 자동납부 월 1회, 월 최대 5천원',
        condition: { min_performance: 100000 },
        action: { type: 'PERCENT', value: 5 },
        limit_config: { monthly_count: 1, monthly_amount: 5000 },
    },
    {
        id: 'sh_nara_sports',
        card_id: 'shinhan_nara',
        category: 'life',
        included_brands: ['sports_leisure'],
        description: '스포츠/레저 5% 할인',
        detail: '전월 10만원 이상, 월 최대 6천원',
        condition: { min_performance: 100000 },
        action: { type: 'PERCENT', value: 5 },
        limit_config: { monthly_amount: 6000 },
    },
    {
        id: 'sh_nara_delivery',
        card_id: 'shinhan_nara',
        category: 'delivery',
        included_brands: ['baemin'],
        description: '배달의민족 5% 할인',
        detail: '전월 10만원 이상, 앱 내 카드결제, 일 1회/월 5회, 건당 1천원·월 5천원 한도',
        condition: { min_performance: 100000 },
        action: { type: 'PERCENT', value: 5, max_discount: 1000 },
        limit_config: { daily_count: 1, monthly_count: 5, monthly_amount: 5000 },
        platform_type: 'ONLINE',
    },
    {
        id: 'sh_nara_ott',
        card_id: 'shinhan_nara',
        category: 'subscription',
        included_brands: ['youtube', 'tving', 'netflix'],
        description: 'OTT 10% 할인',
        detail: '전월 10만원 이상, 공식 정기결제, 월 최대 5천원',
        condition: { min_performance: 100000 },
        action: { type: 'PERCENT', value: 10 },
        limit_config: { monthly_amount: 5000 },
        platform_type: 'OFFICIAL_SITE',
    },
    {
        id: 'sh_nara_fashion',
        card_id: 'shinhan_nara',
        category: 'shopping',
        included_brands: ['musinsa', '29cm'],
        description: '무신사/29CM 10% 할인',
        detail: '전월 10만원 이상, 공식 홈페이지/앱, 월 최대 6천원',
        condition: { min_performance: 100000 },
        action: { type: 'PERCENT', value: 10 },
        limit_config: { monthly_amount: 6000 },
        platform_type: 'OFFICIAL_SITE',
    },
    {
        id: 'sh_nara_cgv_fixed',
        card_id: 'shinhan_nara',
        category: 'movie',
        included_brands: ['cgv'],
        description: 'CGV 2D 영화 6천원 고정가',
        detail: '전월 10만원 이상, 월 1회',
        condition: { min_performance: 100000 },
        action: { type: 'FIXED_PRICE', value: 6000 },
        limit_config: { monthly_count: 1 },
    },
    {
        id: 'sh_nara_amusement',
        card_id: 'shinhan_nara',
        category: 'movie',
        included_brands: ['everland', 'lotte_world', 'seoul_land'],
        description: '테마파크 50% 할인',
        detail: '전월 30만원 이상, 각 놀이공원 일 1회/연 3회',
        condition: { min_performance: 300000 },
        action: { type: 'PERCENT', value: 50 },
        limit_config: { daily_count: 1, yearly_count: 3 },
    },
    {
        id: 'sh_nara_caribbean',
        card_id: 'shinhan_nara',
        category: 'movie',
        included_brands: ['caribbean'],
        description: '캐리비안베이 30% 할인',
        detail: '전월 30만원 이상, 일 1회/연 3회',
        condition: { min_performance: 300000 },
        action: { type: 'PERCENT', value: 30 },
        limit_config: { daily_count: 1, yearly_count: 3 },
    },
    {
        id: 'sh_nara_overseas',
        card_id: 'shinhan_nara',
        category: 'etc',
        included_brands: ['overseas_payment'],
        description: '해외 이용 1% 할인',
        detail: '전월 실적 없음',
        condition: {},
        action: { type: 'PERCENT', value: 1 },
        limit_config: {},
        uses_card_limit: false,
    },
    {
        id: 'sh_nara_cu_event',
        card_id: 'shinhan_nara',
        category: 'convenience',
        included_brands: ['cu_event'],
        description: 'CU 행사상품 10% 할인',
        detail: '전월 실적 없음, 월 최대 5천원',
        condition: {},
        action: { type: 'PERCENT', value: 10 },
        limit_config: { monthly_amount: 5000 },
        uses_card_limit: false,
        platform_type: 'OFFLINE',
    },

    // KB국민 노리2 학생증체크카드
    {
        id: 'kb_nori2_coffee',
        card_id: 'kb_nori2_student',
        category: 'cafe',
        included_brands: ['starbucks', 'coffeebean'],
        description: '커피 10% 할인',
        detail: '스타벅스/커피빈, 전월 실적 없음, 월 최대 3천원',
        condition: {},
        action: { type: 'PERCENT', value: 10 },
        limit_config: { monthly_amount: 3000 },
        uses_card_limit: false,
    },
    {
        id: 'kb_nori2_app_market',
        card_id: 'kb_nori2_student',
        category: 'shopping',
        included_brands: ['google_play', 'app_store'],
        description: '앱마켓 10% 할인',
        detail: '전월 20만원 이상, 월 최대 5천원',
        condition: { min_performance: 200000 },
        action: { type: 'PERCENT', value: 10 },
        limit_config: { monthly_amount: 5000 },
    },
    {
        id: 'kb_nori2_ticket',
        card_id: 'kb_nori2_student',
        category: 'shopping',
        included_brands: ['interpark_ticket'],
        description: '인터파크 티켓 10% 할인',
        detail: '전월 20만원 이상, 월 최대 7천원',
        condition: { min_performance: 200000 },
        action: { type: 'PERCENT', value: 10 },
        limit_config: { monthly_amount: 7000 },
    },
    {
        id: 'kb_nori2_life',
        card_id: 'kb_nori2_student',
        category: 'life',
        included_brands: ['oliveyoung', 'beauty_hair'],
        description: '올리브영/뷰티 5% 할인',
        detail: '전월 20만원 이상, 월 최대 2천원',
        condition: { min_performance: 200000 },
        action: { type: 'PERCENT', value: 5 },
        limit_config: { monthly_amount: 2000 },
    },
    {
        id: 'kb_nori2_convenience',
        card_id: 'kb_nori2_student',
        category: 'convenience',
        included_brands: ['gs25', 'cu'],
        description: '편의점 5% 할인',
        detail: '전월 20만원 이상, 월 최대 2천원',
        condition: { min_performance: 200000 },
        action: { type: 'PERCENT', value: 5 },
        limit_config: { monthly_amount: 2000 },
    },
    {
        id: 'kb_nori2_ott',
        card_id: 'kb_nori2_student',
        category: 'subscription',
        included_brands: ['netflix', 'youtube'],
        description: 'OTT 1천원 할인',
        detail: '전월 20만원 이상, 1만원 이상 결제, 월 2회/최대 2천원',
        condition: { min_spend: 10000, min_performance: 200000 },
        action: { type: 'FLAT', value: 1000 },
        limit_config: { monthly_count: 2, monthly_amount: 2000 },
    },
    {
        id: 'kb_nori2_delivery',
        card_id: 'kb_nori2_student',
        category: 'delivery',
        included_brands: ['baemin', 'yogiyo'],
        description: '배달앱 1천원 할인',
        detail: '전월 20만원 이상, 1만원 이상 결제, 월 1회',
        condition: { min_spend: 10000, min_performance: 200000 },
        action: { type: 'FLAT', value: 1000 },
        limit_config: { monthly_count: 1, monthly_amount: 1000 },
    },
    {
        id: 'kb_nori2_telecom',
        card_id: 'kb_nori2_student',
        category: 'transport',
        included_brands: ['telecom'],
        description: '통신요금 2,500원 할인',
        detail: '전월 20만원 이상, 자동납부 5만원 이상, 월 1회',
        condition: { min_spend: 50000, min_performance: 200000 },
        action: { type: 'FLAT', value: 2500 },
        limit_config: { monthly_count: 1, monthly_amount: 2500 },
    },
    {
        id: 'kb_nori2_cgv',
        card_id: 'kb_nori2_student',
        category: 'movie',
        included_brands: ['cgv'],
        description: 'CGV 4천원 할인',
        detail: '전월 20만원 이상, 1만원 이상 결제, 월 2회/최대 8천원',
        condition: { min_spend: 10000, min_performance: 200000 },
        action: { type: 'FLAT', value: 4000 },
        limit_config: { monthly_count: 2, monthly_amount: 8000 },
    },
    {
        id: 'kb_nori2_amusement',
        card_id: 'kb_nori2_student',
        category: 'movie',
        included_brands: ['everland', 'lotte_world'],
        description: '테마파크 15,000원 할인',
        detail: '전월 20만원 이상, 3만원 이상 결제, 월 1회',
        condition: { min_spend: 30000, min_performance: 200000 },
        action: { type: 'FLAT', value: 15000 },
        limit_config: { monthly_count: 1, monthly_amount: 15000 },
    },

    // 하나 나라사랑카드
    {
        id: 'hana_nara_px',
        card_id: 'hana_nara',
        category: 'etc',
        included_brands: ['military_px'],
        description: 'PX/군마트 20~30% 할인',
        detail: '전월 실적 없음. 10만원 미만 결제 30% 월 5천원, 10만원 이상 결제 20% 별도 한도',
        condition: {},
        action: { type: 'PERCENT', value: 30, max_discount: 5000 },
        limit_config: { monthly_amount: 5000 },
        uses_card_limit: false,
    },
    {
        id: 'hana_nara_easy_shopping',
        card_id: 'hana_nara',
        category: 'shopping',
        included_brands: ['coupang', 'naver_plus_store'],
        description: '쿠팡/네이버플러스 스토어 20% 할인',
        detail: '전월 실적 없음, 일 최대 1천원/월 최대 3천원',
        condition: {},
        action: { type: 'PERCENT', value: 20, max_discount: 1000 },
        limit_config: { daily_count: 1, monthly_amount: 3000 },
        uses_card_limit: false,
        platform_type: 'ONLINE',
    },
    {
        id: 'hana_nara_cu_event',
        card_id: 'hana_nara',
        category: 'convenience',
        included_brands: ['cu_event'],
        description: 'CU 행사상품 10% 할인',
        detail: '전월 실적 없음, 월 최대 5만원. 국군의날/현충일 등 이벤트일 30%',
        condition: {},
        action: { type: 'PERCENT', value: 10 },
        limit_config: { monthly_amount: 50000 },
        uses_card_limit: false,
        platform_type: 'OFFLINE',
    },
    {
        id: 'hana_nara_transport',
        card_id: 'hana_nara',
        category: 'transport',
        included_brands: ['transport_public'],
        description: '대중교통 20% 할인',
        detail: '전월 10만원 이상, 월 최대 1만원',
        condition: { min_performance: 100000 },
        action: { type: 'PERCENT', value: 20 },
        limit_config: { monthly_amount: 10000 },
    },
    {
        id: 'hana_nara_military_resort',
        card_id: 'hana_nara',
        category: 'etc',
        included_brands: ['military_resort'],
        description: '군 콘도 20% 할인',
        detail: '전월 10만원 이상, 월 최대 1만원',
        condition: { min_performance: 100000 },
        action: { type: 'PERCENT', value: 20 },
        limit_config: { monthly_amount: 10000 },
    },
    {
        id: 'hana_nara_starbucks',
        card_id: 'hana_nara',
        category: 'cafe',
        included_brands: ['starbucks'],
        description: '스타벅스 20% 할인',
        detail: '전월 10만원 이상, 1만원 이상, 건당 최대 4천원',
        condition: { min_spend: 10000, min_performance: 100000 },
        action: { type: 'PERCENT', value: 20, max_discount: 4000 },
        limit_config: {},
    },
    {
        id: 'hana_nara_restaurant',
        card_id: 'hana_nara',
        category: 'food',
        included_brands: ['outback', 'vips'],
        description: '아웃백/VIPS 20% 할인',
        detail: '전월 10만원 이상, 1만원 이상, 월 최대 2만원',
        condition: { min_spend: 10000, min_performance: 100000 },
        action: { type: 'PERCENT', value: 20 },
        limit_config: { monthly_amount: 20000 },
    },
    {
        id: 'hana_nara_fastfood',
        card_id: 'hana_nara',
        category: 'food',
        included_brands: ['lotteria', 'mcdonalds', 'burgerking', 'momstouch', 'kfc', 'subway'],
        description: '패스트푸드 5% 할인',
        detail: '전월 10만원 이상, 1만원 이상, 월 최대 2천원',
        condition: { min_spend: 10000, min_performance: 100000 },
        action: { type: 'PERCENT', value: 5 },
        limit_config: { monthly_amount: 2000 },
    },
    {
        id: 'hana_nara_online_shopping',
        card_id: 'hana_nara',
        category: 'shopping',
        included_brands: ['musinsa', '29cm', 'gmarket', 'auction', 'elevenst'],
        description: '온라인 쇼핑 10% 할인',
        detail: '전월 10만원 이상, 1만원 이상, 월 최대 5천원',
        condition: { min_spend: 10000, min_performance: 100000 },
        action: { type: 'PERCENT', value: 10 },
        limit_config: { monthly_amount: 5000 },
        platform_type: 'ONLINE',
    },
    {
        id: 'hana_nara_language',
        card_id: 'hana_nara',
        category: 'shopping',
        included_brands: ['toeic', 'opic', 'teps', 'jpt', 'hsk'],
        description: '어학시험 5% 할인',
        detail: '전월 10만원 이상, 월 최대 5천원',
        condition: { min_performance: 100000 },
        action: { type: 'PERCENT', value: 5 },
        limit_config: { monthly_amount: 5000 },
    },
    {
        id: 'hana_nara_book',
        card_id: 'hana_nara',
        category: 'shopping',
        included_brands: ['kyobo', 'aladin'],
        description: '서점 5% 할인',
        detail: '전월 10만원 이상, 월 최대 5천원',
        condition: { min_performance: 100000 },
        action: { type: 'PERCENT', value: 5 },
        limit_config: { monthly_amount: 5000 },
    },
    {
        id: 'hana_nara_wide_transport',
        card_id: 'hana_nara',
        category: 'transport',
        included_brands: ['rail', 'intercity_bus'],
        description: '광역교통 5% 할인',
        detail: '전월 10만원 이상, KTX/SRT/ITX·고속/시외버스, 월 최대 2천원',
        condition: { min_performance: 100000 },
        action: { type: 'PERCENT', value: 5 },
        limit_config: { monthly_amount: 2000 },
    },
    {
        id: 'hana_nara_amusement',
        card_id: 'hana_nara',
        category: 'movie',
        included_brands: ['everland', 'lotte_world'],
        description: '테마파크 50% 할인',
        detail: '전월 10만원 이상, 월 1회',
        condition: { min_performance: 100000 },
        action: { type: 'PERCENT', value: 50 },
        limit_config: { monthly_count: 1 },
    },
    {
        id: 'hana_nara_salary_taxi',
        card_id: 'hana_nara',
        category: 'transport',
        included_brands: ['taxi', 'kakaot'],
        description: '택시/카카오T 20% 할인',
        detail: '군 급여이체 조건, 월 최대 5천원',
        condition: { manual_check_required: true, required_note: '군 급여이체 조건 확인 필요' },
        action: { type: 'PERCENT', value: 20 },
        limit_config: { monthly_amount: 5000 },
        uses_card_limit: false,
    },
    {
        id: 'hana_nara_salary_delivery',
        card_id: 'hana_nara',
        category: 'delivery',
        included_brands: ['baemin', 'coupangeats', 'yogiyo'],
        description: '배달앱 20% 할인',
        detail: '군 급여이체 조건, 월 최대 5천원',
        condition: { manual_check_required: true, required_note: '군 급여이체 조건 확인 필요' },
        action: { type: 'PERCENT', value: 20 },
        limit_config: { monthly_amount: 5000 },
        uses_card_limit: false,
        platform_type: 'ONLINE',
    },
    {
        id: 'hana_nara_salary_digital',
        card_id: 'hana_nara',
        category: 'subscription',
        included_brands: ['app_store', 'google_play', 'youtube', 'netflix', 'naver_plus', 'coupang_wow', 'naver_webtoon'],
        description: '디지털라이프 10% 할인',
        detail: '군 급여이체 조건, 월 최대 2천원',
        condition: { manual_check_required: true, required_note: '군 급여이체 조건 확인 필요' },
        action: { type: 'PERCENT', value: 10 },
        limit_config: { monthly_amount: 2000 },
        uses_card_limit: false,
        platform_type: 'ONLINE',
    },

    // 하나 트래블로그 학생증 체크카드
    {
        id: 'hana_travelog_overseas_fee',
        card_id: 'hana_travelog_student',
        category: 'etc',
        included_brands: ['overseas_payment', 'overseas_transport'],
        description: '해외 가맹점 수수료 면제',
        detail: '국제브랜드 1% 및 해외서비스 수수료 면제, 전월 실적 없음',
        condition: {},
        action: { type: 'PERCENT', value: 1 },
        limit_config: {},
        uses_card_limit: false,
    },
    {
        id: 'hana_travelog_domestic',
        card_id: 'hana_travelog_student',
        description: '국내 가맹점 0.3% 하나머니 적립',
        detail: '전월 실적/월 한도 없음. 세금·공과금·보험료·상품권 등 일부 항목 제외',
        condition: {},
        action: { type: 'PERCENT', value: 0.3 },
        limit_config: {},
        uses_card_limit: false,
    },
];
